name: studydeck_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  another_flushbar:
  cached_network_image:
  dio:
  flutter:
    sdk: flutter
  intl:
  permission_handler:
  shared_preferences:
  stacked:
  stacked_services:
  url_launcher:
  easy_localization:
  animated_bottom_navigation_bar: ^1.3.3
  fluentui_system_icons: ^1.1.259
  fui_kit: ^2.0.2
  flutter_expandable_fab: ^2.3.0
  flutter_iconpicker: ^4.0.1
  file_picker: ^9.1.0
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints:
  mockito:
  stacked_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Poppins/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
